news/urls.py
from django.urls import path
from .views import *

app_name = 'news'

urlpatterns = [
    path('create/', NewsCreateViews.as_view(), name='create'),
    path('delete/<int:pk>/', NewsDeleteViews.as_view(), name='delete'),
    path('Update/<int:pk>/', NewsUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', NewsDateilViews.as_view(), name='detail'),
    path('', NewsListViews.as_view(), name='list')
]

university/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls', namespace='news'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from ckeditor.fields import RichTextField


class CategoryModel(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class NewsModel(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='news')
    short_descriptions = models.TextField()
    long_descriptions = models.TextField(null=True)
    category = models.ForeignKey(CategoryModel,
                                 on_delete=models.PROTECT,
                                 related_name='news')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'news'
        verbose_name_plural = 'news'

news/forms.py
from django import forms
from .models import *


class NewsModelForm(forms.ModelForm):
    class Meta:
        model = NewsModel
        exclude = ['created_at']

news/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import *
from news.forms import NewsModelForm, CategoryModel
from django.urls import reverse


class NewsListViews(ListView):
    template_name = 'index.html'
    paginate_by = 6

    def get_queryset(self):
        qs = NewsModel.objects.order_by('-pk')
        q = self.request.GET.get('q')

        cat = self.request.GET.get('cat')

        if q:
            qs = qs.filter(title__icontains=q)
        if cat:
            qs = qs.filter(category__id=cat)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        return context


class NewsCreateViews(CreateView):
    form_class = NewsModelForm
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('news:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        return context


class NewsUpdateView(UpdateView):
    form_class = NewsModelForm
    template_name = 'form.html'
    model = NewsModel

    def get_success_url(self):
        return reverse('news:list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        return context


class NewsDeleteViews(DeleteView):
    model = NewsModel

    def get_success_url(self):
        return reverse('news:list')


class NewsDateilViews(DetailView):
    model = NewsModel
    template_name = 'News_detail.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>University</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

{% block content %}{% endblock %}

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <div class="col-6 offset-3">
            <form action="{% url 'news:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label }}:
                        {{ field|add_class:'form-control'}}
                    </div>
                {% endfor %}
                <div>
                    <button class="w-100 btn btn-success" type="submit">Create</button>
                </div>

            </form>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            {% for i in object_list %}
                <div class="col-lg-4">
                    <h3 style="word-wrap:break-word;">{{ i.title }}</h3>
                    <img class="img-fluid" src="{{ i.image.url }}" alt="">
                    <p style="word-wrap:break-word;">{{ i.short_descriptions }}</p>
                    <p>{{ i.created_at | date:'d.m.Y H:i' }} {{ i.category }}</p>

                    <div class="row">
<!--                        <div class="col-lg-4">-->
<!--                            <a class="btn btn-primary" href="{% url 'news:update' pk=i.pk %}"> update-->
<!--                            </a>-->
<!--                        </div>-->
                        <div class="col-lg-4">
                            <form onsubmit="return confirm('You sure?')" method="POST"
                                  action="{% url 'news:delete' pk=i.pk %}">
                                {% csrf_token %}
                                <button class="btn btn-danger" type="submit"> delete
                                    <i class="fa fa-trash text-danger"></i>
                                </button>
                            </form>
                        </div>
                        <div class="col-lg-4">
                            <a class="btn btn-primary" href="{% url 'news:detail' pk=i.pk %}">Batafsil</a>
                        </div>
                    </div>
                </div>


            {% endfor %}
        </div>
        <button class="btn btn-success float-right btn-lg">
            <a class="text-light a" href="{% url 'news:create' %} "> create news</a>
        </button>
    </div>
{% endblock %}

templates/news_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <h3>{{ object.title }}</h3>
        <img class="img-fluid" src="{{ object.image.url }}" alt="">
        <p style="word-wrap:break-word;">{{ object.long_descriptions }}</p>
        <p>{{ object.created_at|date:'d.m.Y H:i' }} {{ object.category }}</p>
    </div>
{% endblock %}